title: Cellular Automata DS
description: Homebrew cellular automata simulator for the Nintendo DS.
google_analytics:
show_downloads: true
theme: jekyll-theme-hacker
zip_url: https://github.com/aldatsa/cellular-automata-ds/archive/v0.10.6.0.zip
tar_url: https://github.com/aldatsa/cellular-automata-ds/archive/v0.10.6.0.tar.gz
nds_url: https://github.com/aldatsa/cellular-automata-ds/releases/download/v0.10.6.0/cellular-automata-ds.nds

gems:
  - jekyll-mentions
